development:
  BASIC_AUTH_USERNAME: 'BASIC_AUTH_USERNAME'
  BASIC_AUTH_PASSWORD: 'BASIC_AUTH_PASSWORD'
  SECRET_KEY_BASE:     '12345678901234567890123456789012'
  TWILIO_SID:          'TWILIO_SID'
  TWILIO_TOKEN:        'TWILIO_TOKEN'
  DEFAULT_FROM_NUMBER: '+16131234567'